CREATE TABLE QUIZ_TAKER(
	ID SERIAL INT PRIMARY KEY,
	USERNAME VARCHAR(50),
	SCORE INT
);

CREATE TABLE QUESTION(
	ID SERIAL INT PRIMARY KEY,
	QUESTION_TEXT VARCHAR(255),
	OPTION_0 VARCHAR(255),
	OPTION_1 VARCHAR(255),
	OPTION_2 VARCHAR(255),
	OPTION_3 VARCHAR(255),
	CORRECT_OPTION_INDEX INT
);